import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import NavBar from "./navbar/page";
import Footer from "./footer/page";
import Preloader from "./preloader/page";
import CardSection from "./services/page";
import FrequentQuestions from "./frequentquestions/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Preloader />
            <NavBar/>
            {children}
            <CardSection/>
            <FrequentQuestions />
            <Footer />
       
       
        </body>
    </html>
  );
}
